import type { Metadata } from "next";
import localFont from 'next/font/local'
import "../styles/globals.css";

const poppins = localFont({
  src: [
    { path: '../fonts/Poppins-Regular.woff2', weight: '400' },
    { path: '../fonts/Poppins-Medium.woff2', weight: '500' },
    { path: '../fonts/Poppins-SemiBold.woff2', weight: '600' },
    { path: '../fonts/Poppins-Bold.woff2', weight: '700' },
  ],
  variable: '--font-poppins',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="pl" className={poppins.variable} suppressHydrationWarning>
      <body suppressHydrationWarning>{children}</body>
    </html>
  );
}
